#############################################
# Here i save all the variables for hyprland#
#############################################

$mainMod = SUPER # Sets "Windows" key as main modifier
$terminal = kitty
$fileManager = dolphin
$browser = firefox


#############################
### ENVIRONMENT VARIABLES ###
#############################

env = XCURSOR_THEME, LyraB-cursors
env = HYPRCURSOR_THEME, LyraB-cursors
env = XCURSOR_SIZE,12
env = HYPRCURSOR_SIZE,12