#############################################
# Here i save all the variables for hyprland#
#############################################

$mainMod = SUPER 
$terminal = kitty
$fileManager = kitty yazi
$browser = firefox
$editor = codium







#############################
### ENVIRONMENT VARIABLES ###
#############################

env = XCURSOR_THEME, LyraB-cursors
env = HYPRCURSOR_THEME, LyraB-cursors
env = XCURSOR_SIZE,12
env = HYPRCURSOR_SIZE,12